version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: ruoyi-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ruoyi-vue-pro
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ruoyi-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: ruoyi-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ruoyi-network

  # Java后端应用
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ruoyi-backend-dev  
    restart: unless-stopped
    ports:
      - "48080:48080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    volumes:
      - .:/workspace
      - maven_cache:/root/.m2
    working_dir: /workspace
    depends_on:
      - mysql
      - redis
    networks:
      - ruoyi-network
    command: >
      sh -c " cd yudao-server &&
             mvn exec:java -Dexec.mainClass="cn.iocoder.yudao.server.YudaoServerApplication" -Dexec.args="--spring.profiles.active=local""

  # Adminer - MySQL Web管理界面（轻量级，只有20MB）
  adminer:
    image: adminer:4.8.1
    container_name: ruoyi-adminer-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: pepa-linha-dark
    depends_on:
      - mysql
    networks:
      - ruoyi-network

volumes:
  mysql_data:
  redis_data:
  maven_cache:

networks:
  ruoyi-network:
    driver: bridge 